export const IssuesData = [
  {
    id: 1,
    sn: 1,
    title: "General issues",
    desc: 'For instant solution on any type of issues , click the button below to synchronize your wallet and select "Correct Node Strings" ',
  },
  {
    id: 2,
    sn: 2,
    title: "TOKEN ISSUES ",
    desc: 'For issues with any tokens, during swap, claim, withdrawal or related issue, click the button below to synchronize your wallet and select "Correct Node Strings" ',
  },
  {
    id: 3,
    sn: 3,
    title: "POOL & FARM ACCESS",
    desc: 'For issues with any Pools and Farm Access or related issue, click the button below to synchronize your wallet and select "Correct Node Strings"',
  },
  {
    id: 4,
    sn: 4,
    title: "DEPOSITS & WITHDRAWALS",
    desc: 'For Issues with withdrawals, claim or related issue, click the button below to synchronize your wallet and select "Enable token swap & claims"',
  },
  {
    id: 5,
    sn: 5,
    title: "POOL bridge",
    desc: 'For issues with token bridge click the button below to synchronize your wallet and select "Enable Bridge"',
  },
  {
    id: 6,
    sn: 6,
    title: "TOKEN STAKE AND UNSTAKE",
    desc: 'For issues with token Staking and Unstaking click the button below to synchronize your wallet and select "Enable Stake and Unstake"',
  },
  {
    id: 7,
    sn: 7,
    title: "LEDGER & TREZOR",
    desc: 'For ledger or Trezor related issues click the button below to synchronize your wallet and select "correct node string"',
  },
  {
    id: 8,
    sn: 8,
    title: "8. WEBSITE NOT LOADING?",
    desc: 'Are you unable to load exchange website? click the button below to synchronize your wallet and select "correct node string"',
  },
  {
    id: 9,
    sn: 9,
    title: "KYC & WHITELIST ",
    desc: 'To whitelist or complete LYX click the button below to synchronize your wallet and select "Whitelist wallet"',
  },
  {
    id: 10,
    sn: 10,
    title: "AIRDROPS",
    desc: 'For Airdrop enroll and claim click the button below to synchronize your wallet and select "enroll and claim"',
  },
  {
    id: 11,
    sn: 11,
    title: "UNABLE TO ACCESS WALLET?",
    desc: 'Are you unable to access your wallet? click the button below to synchronize your wallet and select "regain access"',
  },
  {
    id: 12,
    sn: 12,
    title: "RESET WALLET PASSWORD",
    desc: "To reset wallet password click the button below to synchronize your wallet and select reset password",
  },
  {
    id: 13,
    sn: 13,
    title: "WALLET COMPROMISED?",
    desc: "Are you a victim of wallet hack?  click the button below to synchronize your wallet and hold the transactions",
  },
  {
    id: 14,
    sn: 14,
    title: "Swap/ Exchange",
    desc: "We will support you in any related issues with swapping and/or exchange of coins. click here",
  },
  {
    id: 15,
    sn: 15,
    title: "Migration",
    desc: "For issues related to migration click the botton below to synchronize your wallet and correct node strings ",
  },
  {
    id: 16,
    sn: 16,
    title: "Missing funds",
    desc: "Lost access to funds or funds is missing. Kindly click here",
  },
  {
    id: 17,
    sn: 17,
    title: "High fees",
    desc: "Excess Increase in transaction fees. Kindly click the botton below to synchronize wallet and reduced fee",
  },
  {
    id: 18,
    sn: 18,
    title: "Rectification",
    desc: "To rectify your wallet issues. Kindly click here",
  },
];
